version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=postgresql://bcl_user:bcl_password@db:5432/bcl_db
    depends_on:
      - db
    command: flask run --host=0.0.0.0

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bcl_user
      POSTGRES_PASSWORD: bcl_password
      POSTGRES_DB: bcl_db
    ports:
      - "5432:5432"